# Generated by Django 5.0.4 on 2024-08-12 10:14

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[store.models.validate_price]),
        ),
    ]
