# Generated by Django 5.1.1 on 2024-09-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_status_alter_category_created'),
        ('store', '0005_alter_order_customer_alter_products_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='products',
            unique_together={('slug', 'category')},
        ),
    ]
