# Generated by Django 5.1.1 on 2024-09-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_status_alter_category_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='keyword',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
